
import qrcode
import base64
from io import BytesIO
from typing import Tuple

def generate_qr_image_and_payload(
    student_id: str, 
    roll_number: str, 
    seat_id: str, 
    exam_id: str, 
    unique_token: str
) -> Tuple[str, str]:
    """
    Generates a QR code image (Base64) and the raw payload string.
    
    Args:
        student_id: The student's unique ID.
        roll_number: The student's roll number.
        seat_id: The final, assigned seat (e.g., 'A01_S5').
        exam_id: Identifier for the exam.
        unique_token: A security token generated by the Backend.
        
    Returns:
        (base64_image: str, raw_payload: str)
    """
    
    # 1. Assemble the Raw Payload String
    # Format: ID:{student_id}|ROLL:{roll_number}|SEAT:{seat_id}|EXAM:{exam_id}|TOKEN:{unique_token}
    raw_payload = f"ID:{student_id}|ROLL:{roll_number}|SEAT:{seat_id}|EXAM:{exam_id}|TOKEN:{unique_token}"
    
    # 2. Generate QR Code Image
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=4, # Compact size
        border=2,
    )
    qr.add_data(raw_payload)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    
    # 3. Convert Image to Base64 (string format for API transfer/embedding)
    buffered = BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
    
    return img_str, raw_payload
